//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.Budget_Transaction = new HashSet<Budget_Transaction>();
            this.User_Budget = new HashSet<User_Budget>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int BudgetId { get; set; }
        public int AcctId { get; set; }
        public decimal Balance { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Budget_Transaction> Budget_Transaction { get; set; }
        public virtual ICollection<User_Budget> User_Budget { get; set; }
    }
}
