//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.GroupBudgets = new HashSet<GroupBudget>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<GroupBudget> GroupBudgets { get; set; }
    }
}
