//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupBudget
    {
        public GroupBudget()
        {
            this.GroupBudget_Transaction = new HashSet<GroupBudget_Transaction>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int GroupBudgetId { get; set; }
        public int GroupId { get; set; }
        public decimal balance { get; set; }
        public Nullable<int> TransType { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<GroupBudget_Transaction> GroupBudget_Transaction { get; set; }
        public virtual TransType TransType1 { get; set; }
    }
}
