//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Users
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int Group_UsersId { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
