//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransId { get; set; }
        public int GroupId { get; set; }
        public int AcctId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int TransType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
