//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Budget_Transaction = new HashSet<Budget_Transaction>();
            this.GroupBudget_Transaction = new HashSet<GroupBudget_Transaction>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int TransId { get; set; }
        public int AcctId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int TransType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int PrimaryKey { get { return TransId; } }
    
        public virtual TransType TransType1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Budget_Transaction> Budget_Transaction { get; set; }
        public virtual ICollection<GroupBudget_Transaction> GroupBudget_Transaction { get; set; }
    }
}
