//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Transaction
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int TransId { get; set; }
        public int AcctId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int TransType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual TransType TransType1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
