//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseBudgetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Budgets = new HashSet<Budget>();
            this.Transactions = new HashSet<Transaction>();
        }


        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserBudget { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
